name: .NET Framework CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'  # Change to your desired .NET Framework version

    - name: Restore NuGet packages
      run: |
        cd path/to/solution/folder  # Replace with the actual path to the folder containing WebApplication3.sln
        dotnet restore WebApplication3.sln

    - name: Build
      run: |
        cd path/to/solution/folder  # Replace with the actual path to the folder containing WebApplication3.sln
        dotnet build WebApplication3.sln --configuration Release

  test:
    runs-on: windows-latest

    steps:
    # Similar setup and restore steps as the 'build' job

    - name: Test
      run: |
        cd path/to/solution/folder  # Replace with the actual path to the folder containing WebApplication3.sln
        dotnet test WebApplication3.Tests/WebApplication3.Tests.csproj --configuration Release

  deploy:
    runs-on: windows-latest

    steps:
    # Similar setup and restore steps as the 'build' job

    - name: Deploy
      run: |
        # Add deployment steps here to deploy "WebApp" to the staging environment

  notify-on-failure:
    runs-on: windows-latest
    if: ${{ failure() }}

    steps:
    - name: Notify on Failure
      run: |
        echo "Build or deployment failed for $GITHUB_REPOSITORY"
